# Runtime Stage (JAR는 GitHub Actions에서 빌드)
FROM eclipse-temurin:21-jre
WORKDIR /app

COPY user-server/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", \
  "-XX:+UseG1GC", \
  "-XX:MaxRAMPercentage=75.0", \
  "-jar", "app.jar"]
