# ---------- Build Stage ----------
FROM eclipse-temurin:21-jdk AS builder
WORKDIR /app

# Gradle Wrapper
COPY . .
RUN chmod +x gradlew
RUN ./gradlew clean :user-server:bootJar -x test

# ---------- Runtime Stage ----------
FROM eclipse-temurin:21-jre
WORKDIR /app

# user-server bootJar만 복사
COPY --from=builder /app/user-server/build/libs/*.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", \
  "-XX:+UseG1GC", \
  "-XX:MaxRAMPercentage=75.0", \
  "-jar", "app.jar"]
