SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM comment_like;
DELETE FROM `comment`;
DELETE FROM emotion;
DELETE FROM post_image;
DELETE FROM post_hashtag;
DELETE FROM posts;
DELETE FROM hashtag;
DELETE FROM user_block;
DELETE FROM users;
DELETE FROM baseball_teams;
SET FOREIGN_KEY_CHECKS = 1;
